<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Редактор "CodeMirror"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Универсальный текстовый редактор, реализованный в JavaScript для браузера. Он специализируется на редактировании кода и поставляется с более чем 100 языковыми режимами и различными дополнениями, реализующими более продвинутый функционал редактирования.</p>
    <p>Сайт: <a target="_blank" href="https://codemirror.net/">https://codemirror.net/</a></p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Настройка редактора "CodeMirror"</a></li>
    </ul>
</article>