<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Editor "CodeMirror"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Universal text editor implemented in JavaScript for the browser. It specializes in code editing and comes with over 100 language modes and various add-ons for more advanced editing functionality.</p>
    <p>Сайт: <a target="_blank" href="https://codemirror.net/">https://codemirror.net/</a></p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Customizing Editor "CodeMirror"</a></li>
    </ul>
</article>